# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202305

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [12]:
# create some random matrices
from ftplib import CRLF


A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

print(np.round(A, 2), CRLF*2, np.round(B, 2), CRLF*2, np.round(C, 2))

[[-1.29 -0.67 -0.6   0.57]
 [-0.61  0.28 -0.49  0.56]
 [ 0.12 -0.76 -0.66  1.  ]] 

 [[-0.51 -0.28  1.48 -0.87  0.68]
 [-0.41 -0.21 -0.8   0.49  1.18]
 [ 0.47 -0.5   0.84 -0.62  0.32]
 [-1.42  0.32  1.8   0.29 -0.88]] 

 [[-0.95 -0.1  -0.37  0.57 -1.46 -1.57 -2.28]
 [-0.69 -1.61  1.68  0.3   0.82  0.88  0.12]
 [-0.51  2.89 -0.72 -0.63 -0.25 -1.3  -1.22]]


In [14]:
# try some multiplications...
print(np.round( A@B   ,2), CRLF)
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[-0.17  0.98 -0.86  1.33 -2.35]
 [-0.83  0.54 -0.53  1.14 -0.74]
 [-1.48  0.77  2.03  0.22 -1.91]] 

[[ 1.58  0.83  1.25 -1.43]
 [ 1.48 -2.58 -1.06  1.92]
 [-0.65  1.26 -0.13  0.02]
 [-1.    0.18 -0.08 -0.13]
 [ 1.35  1.4   0.64 -0.62]
 [ 1.31  2.28  1.37 -1.69]
 [ 2.71  2.49  2.13 -2.45]]


# Using pytorch

In [15]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[ 1.1100, -3.4700,  1.3100, -2.2100,  4.2000,  2.3400,  5.4100],
        [ 1.2300, -2.5000,  1.6700, -2.6900,  1.3000,  1.5600,  4.2100],
        [-0.6000, -1.1300, -0.0100, -0.2600, -0.5600,  0.7300, -0.6700]],
       dtype=torch.float64)
 
tensor([[ 1.1100, -3.4700,  1.3100, -2.2100,  4.2000,  2.3400,  5.4100],
        [ 1.2300, -2.5000,  1.6700, -2.6900,  1.3000,  1.5600,  4.2100],
        [-0.6000, -1.1300, -0.0100, -0.2600, -0.5600,  0.7300, -0.6700]])
