# COURSE: A deep understanding of deep learning
## SECTION: Regularization
### LECTURE: Dropout regularization in practice
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202305

In [14]:
# import libraries
import torch
import torch.nn as nn
import torch.nn.functional as F

# Using dropout

In [15]:
# define a dropout instance and make some data
prob = .5

dropout = nn.Dropout(p=prob)
x = torch.ones(10)

# let's see what dropout returns
y = dropout(x)
# print(x)
# print(y*(1-prob))
# print(torch.mean(y))

# --- MAV ---
dropped = []
for i in range(1000):
	dropped.append(dropout(x))
 
# first 5 rows of dropped
dropped[:5]
# --- MAV ---

[tensor([2., 0., 0., 0., 0., 2., 0., 2., 2., 2.]),
 tensor([0., 0., 2., 2., 0., 2., 0., 0., 2., 0.]),
 tensor([2., 2., 2., 0., 2., 2., 2., 2., 0., 0.]),
 tensor([0., 2., 2., 2., 2., 2., 0., 0., 2., 0.]),
 tensor([0., 2., 2., 0., 0., 2., 0., 0., 2., 2.])]

In [16]:
# --- MAV ---
# mean of dropped
print(torch.mean(torch.stack(dropped), dim=0))

# mean of mean of dropped
print(torch.mean(torch.mean(torch.stack(dropped), dim=0)))
# --- END MAV ---

tensor([1.0280, 0.9900, 1.0380, 1.0240, 0.9540, 1.0420, 0.9940, 1.0340, 1.0720,
        0.9920])
tensor(1.0168)


In [27]:
# dropout is turned off when evaluating the model
dropout.eval()
y = dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [28]:
# annoyingly, F.dropout() is not deactivated in eval mode:
dropout.eval()
y = F.dropout(x)
print(y)
print(torch.mean(y))

tensor([2., 2., 2., 0., 0., 0., 0., 0., 0., 2.])
tensor(0.8000)


In [19]:
# but you can manually switch it off
# dropout.eval()
y = F.dropout(x,training=False)

print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [20]:
# the model needs to be reset (to train) after toggling into eval mode

dropout.train()
y = dropout(x)
print(y) # with dropout


dropout.eval()
y = dropout(x)
print(y) # without dropout


# dropout.train()
y = dropout(x)
print(y) # still w/o dropout ;)

tensor([2., 2., 2., 2., 0., 0., 2., 2., 0., 2.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
