# COURSE: A deep understanding of deep learning
## SECTION: ANNs
### LECTURE: Depth vs. breadth: number of parameters
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202305

In [2]:
# import libraries
import numpy as np
import torch
import torch.nn as nn

In [3]:
# build two models

widenet = nn.Sequential(
    nn.Linear(2,4),  # hidden layer
    nn.Linear(4,3),  # output layer
    )


deepnet = nn.Sequential(
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,3),  # output layer
    )

# print them out to have a look
print(widenet)
print(' ')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [4]:
widenet.named_parameters()

<generator object Module.named_parameters at 0x000000001717E120>

# Peeking inside the network

In [5]:
# check out the parameters
for p in deepnet.named_parameters():
  print(p)
  print(' ')

('0.weight', Parameter containing:
tensor([[-0.5328, -0.6206],
        [-0.5771,  0.0621]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([ 0.3522, -0.5244], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[-0.2265,  0.6295],
        [ 0.6067, -0.5405]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([-0.3826,  0.0478], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[-0.1828,  0.3640],
        [-0.6242,  0.1542],
        [-0.1688, -0.2343]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([-0.4903, -0.6432, -0.5467], requires_grad=True))
 


In [6]:
# count the number of nodes ( = the number of biases)

# named_parameters() is an iterable that returns the tuple (name,numbers)
numNodesInWide = 0
for p in widenet.named_parameters():  # p = (paramName, paramVect)
    print(f'name: {p[0]}, value: {p[1]}')
    if 'bias' in p[0]:
        numNodesInWide += len(p[1]) 

numNodesInDeep = 0
for paramName,paramVect in deepnet.named_parameters():
    if 'bias' in paramName:
        numNodesInDeep += len(paramVect)

print('There are %s nodes in the wide network.' %numNodesInWide)
print('There are %s nodes in the deep network.' %numNodesInDeep)

name: 0.weight, value: Parameter containing:
tensor([[-0.1195,  0.5488],
        [-0.0352,  0.0842],
        [-0.5259, -0.0876],
        [ 0.5637, -0.6075]], requires_grad=True)
name: 0.bias, value: Parameter containing:
tensor([0.5384, 0.6069, 0.2583, 0.1221], requires_grad=True)
name: 1.weight, value: Parameter containing:
tensor([[-0.0818,  0.2248, -0.4278,  0.2057],
        [ 0.2913, -0.0963,  0.0822, -0.4041],
        [-0.2276,  0.4774,  0.3639,  0.4986]], requires_grad=True)
name: 1.bias, value: Parameter containing:
tensor([-0.2315,  0.1890,  0.0168], requires_grad=True)
There are 7 nodes in the wide network.
There are 7 nodes in the deep network.


In [6]:
# just the parameters (not named_parameters)
for p in widenet.parameters():
  print(p)
  print(' ')

Parameter containing:
tensor([[ 0.6969,  0.6295],
        [-0.6807, -0.6436],
        [ 0.5972,  0.3059],
        [-0.1200, -0.4485]], requires_grad=True)
 
Parameter containing:
tensor([ 0.2884, -0.0293, -0.4389, -0.1089], requires_grad=True)
 
Parameter containing:
tensor([[ 0.2303,  0.0314,  0.1269, -0.3146],
        [ 0.0973,  0.1853,  0.0773, -0.2832],
        [-0.0029,  0.0504, -0.0743, -0.1454]], requires_grad=True)
 
Parameter containing:
tensor([ 0.4835, -0.1969,  0.4246], requires_grad=True)
 


In [7]:
# now count the total number of trainable parameters
nparams = 0
for p in widenet.parameters():
  if p.requires_grad:
    print('This piece has %s parameters' %p.numel())
    nparams += p.numel()

print('\n\nTotal of %s parameters'%nparams)

This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


Total of 27 parameters


In [7]:
# btw, can also use list comprehension

nparams = np.sum([ p.numel() for p in widenet.parameters() if p.requires_grad ])
print('Widenet has %s parameters'%nparams)

nparams = np.sum([ p.numel() for p in deepnet.parameters() if p.requires_grad ])
print('Deepnet has %s parameters'%nparams)

Widenet has 27 parameters
Deepnet has 21 parameters


In [9]:
# A nice simple way to print out the model info.
from torchsummary import summary # use 
summary(widenet,(1,2))


### NOTE ABOUT THE CODE IN THIS CELL:
# torchsummary is being replaced by torchinfo.
# If you are importing these libraries on your own (via pip), then see the following website:
#        https://pypi.org/project/torch-summary/
# However, torchsummary will continue to be supported, so if the code in this cell works (meaning torchsummary is already installed), 
# then you don't need to do anything!

ModuleNotFoundError: No module named 'torchsummary'