# COURSE: A deep understanding of deep learning
## SECTION: ANNs
### LECTURE: Depth vs. breadth: number of parameters
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202305

In [1]:
# import libraries
import numpy as np
import torch
import torch.nn as nn

In [2]:
# build two models

widenet = nn.Sequential(
    nn.Linear(2,4),  # hidden layer
    nn.Linear(4,3),  # output layer
    )


deepnet = nn.Sequential(
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,3),  # output layer
    )

# print them out to have a look
print(widenet)
print(' ')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [3]:
widenet.named_parameters()

<generator object Module.named_parameters at 0x0000000016D7AC80>

# Peeking inside the network

In [4]:
# check out the parameters
for p in deepnet.named_parameters():
  print(p)
  print(' ')

('0.weight', Parameter containing:
tensor([[-0.1909,  0.4930],
        [-0.0918,  0.2575]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([-0.4873,  0.4204], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[ 0.2342, -0.3244],
        [-0.6219,  0.6918]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([-0.4375,  0.0925], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[ 0.1869, -0.0593],
        [-0.2409,  0.6335],
        [ 0.5335, -0.0635]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([ 0.0561, -0.0464, -0.6577], requires_grad=True))
 


In [5]:
# count the number of nodes ( = the number of biases)

# named_parameters() is an iterable that returns the tuple (name,numbers)
numNodesInWide = 0
for p in widenet.named_parameters():  # p = (paramName, paramVect)
  if 'bias' in p[0]:
    numNodesInWide += len(p[1]) 

numNodesInDeep = 0
for paramName,paramVect in deepnet.named_parameters():
  if 'bias' in paramName:
    numNodesInDeep += len(paramVect)


print('There are %s nodes in the wide network.' %numNodesInWide)
print('There are %s nodes in the deep network.' %numNodesInDeep)

There are 7 nodes in the wide network.
There are 7 nodes in the deep network.


In [6]:
# just the parameters
for p in widenet.parameters():
  print(p)
  print(' ')

Parameter containing:
tensor([[ 0.6969,  0.6295],
        [-0.6807, -0.6436],
        [ 0.5972,  0.3059],
        [-0.1200, -0.4485]], requires_grad=True)
 
Parameter containing:
tensor([ 0.2884, -0.0293, -0.4389, -0.1089], requires_grad=True)
 
Parameter containing:
tensor([[ 0.2303,  0.0314,  0.1269, -0.3146],
        [ 0.0973,  0.1853,  0.0773, -0.2832],
        [-0.0029,  0.0504, -0.0743, -0.1454]], requires_grad=True)
 
Parameter containing:
tensor([ 0.4835, -0.1969,  0.4246], requires_grad=True)
 


In [7]:
# now count the total number of trainable parameters
nparams = 0
for p in widenet.parameters():
  if p.requires_grad:
    print('This piece has %s parameters' %p.numel())
    nparams += p.numel()

print('\n\nTotal of %s parameters'%nparams)

This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


Total of 27 parameters


In [ ]:
# btw, can also use list comprehension

nparams = np.sum([ p.numel() for p in widenet.parameters() if p.requires_grad ])
print('Widenet has %s parameters'%nparams)

nparams = np.sum([ p.numel() for p in deepnet.parameters() if p.requires_grad ])
print('Deepnet has %s parameters'%nparams)

In [ ]:
# A nice simple way to print out the model info.
from torchsummary import summary
summary(widenet,(1,2))


### NOTE ABOUT THE CODE IN THIS CELL:
# torchsummary is being replaced by torchinfo.
# If you are importing these libraries on your own (via pip), then see the following website:
#        https://pypi.org/project/torch-summary/
# However, torchsummary will continue to be supported, so if the code in this cell works (meaning torchsummary is already installed), 
# then you don't need to do anything!