# COURSE: A deep understanding of deep learning
## SECTION: ANNs
### LECTURE: Depth vs. breadth: number of parameters
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202305

In [1]:
# import libraries
import numpy as np
import torch
import torch.nn as nn

In [2]:
# build two models

widenet = nn.Sequential(
    nn.Linear(2,4),  # hidden layer
    nn.Linear(4,3),  # output layer
    )


deepnet = nn.Sequential(
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,3),  # output layer
    )

# print them out to have a look
print(widenet)
print(' ')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [3]:
widenet.named_parameters()

<generator object Module.named_parameters at 0x0000000016B89C80>

# Peeking inside the network

In [4]:
# check out the parameters
for p in widenet.named_parameters():
  print(p)
  print(' ')

('0.weight', Parameter containing:
tensor([[-0.3047, -0.2450],
        [ 0.5637,  0.2672],
        [-0.6435, -0.2688],
        [ 0.5854,  0.5598]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([ 0.0372, -0.1411,  0.5606, -0.6193], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[-0.0915,  0.1649, -0.3100, -0.4948],
        [ 0.0180,  0.0045, -0.3598, -0.2937],
        [ 0.2275,  0.2837,  0.2302, -0.1031]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([-0.3193,  0.1683,  0.0292], requires_grad=True))
 


In [5]:
# count the number of nodes ( = the number of biases)

# named_parameters() is an iterable that returns the tuple (name,numbers)
numNodesInWide = 0
for p in widenet.named_parameters():  # p = (paramName, paramVect)
    # print(f'name: {p[0]}, value: {p[1]}')
    if 'bias' in p[0]:
        numNodesInWide += len(p[1]) 

numNodesInDeep = 0
for paramName,paramVect in deepnet.named_parameters():
    if 'bias' in paramName:
        numNodesInDeep += len(paramVect)

print('There are %s nodes in the wide network.' %numNodesInWide)
print('There are %s nodes in the deep network.' %numNodesInDeep)

There are 7 nodes in the wide network.
There are 7 nodes in the deep network.


In [6]:
# just the parameters (not named_parameters)
for p in widenet.parameters():
  print(p)
  print(' ')

Parameter containing:
tensor([[-0.3047, -0.2450],
        [ 0.5637,  0.2672],
        [-0.6435, -0.2688],
        [ 0.5854,  0.5598]], requires_grad=True)
 
Parameter containing:
tensor([ 0.0372, -0.1411,  0.5606, -0.6193], requires_grad=True)
 
Parameter containing:
tensor([[-0.0915,  0.1649, -0.3100, -0.4948],
        [ 0.0180,  0.0045, -0.3598, -0.2937],
        [ 0.2275,  0.2837,  0.2302, -0.1031]], requires_grad=True)
 
Parameter containing:
tensor([-0.3193,  0.1683,  0.0292], requires_grad=True)
 


In [7]:
# now count the total number of trainable parameters
nparams = 0
for p in widenet.parameters():
  if p.requires_grad:
    print('This piece has %s parameters' %p.numel())
    nparams += p.numel()

print('\n\nTotal of %s parameters'%nparams)

This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


Total of 27 parameters


In [8]:
# btw, can also use list comprehension

nparams = np.sum([ p.numel() for p in widenet.parameters() if p.requires_grad ])
print('Widenet has %s parameters'%nparams)

nparams = np.sum([ p.numel() for p in deepnet.parameters() if p.requires_grad ])
print('Deepnet has %s parameters'%nparams)

Widenet has 27 parameters
Deepnet has 21 parameters


In [9]:
# %pip install torchsummary

# A nice simple way to print out the model info.
from torchsummary import summary # use 
summary(widenet,(1,2))


### NOTE ABOUT THE CODE IN THIS CELL:
# torchsummary is being replaced by torchinfo.
# If you are importing these libraries on your own (via pip), then see the following website:
#        https://pypi.org/project/torch-summary/
# However, torchsummary will continue to be supported, so if the code in this cell works (meaning torchsummary is already installed), 
# then you don't need to do anything!

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 4]              12
            Linear-2                 [-1, 1, 3]              15
Total params: 27
Trainable params: 27
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


In [11]:
# %pip install torchsummary

# A nice simple way to print out the model info.
from torchsummary import summary # use 
summary(deepnet,(1,2))


### NOTE ABOUT THE CODE IN THIS CELL:
# torchsummary is being replaced by torchinfo.
# If you are importing these libraries on your own (via pip), then see the following website:
#        https://pypi.org/project/torch-summary/
# However, torchsummary will continue to be supported, so if the code in this cell works (meaning torchsummary is already installed), 
# then you don't need to do anything!

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 2]               6
            Linear-2                 [-1, 1, 2]               6
            Linear-3                 [-1, 1, 3]               9
Total params: 21
Trainable params: 21
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


In [ ]:
# create a 